name: '${project.name}'
description: '${project.description}'
version: '${project.version}'
author: 'Snitchi'
main: '${project.groupId}.${project.artifactId}.${project.name}Plugin'
api-version: 1.15

commands:
  sethome:
  home:
  homes:
  workbench:
    aliases: [wb]